import Light from "./components/greetings/components/light";
import Navbar from "./components/navbar";
import "@/styles/globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="layout-container">
          <div style={{ marginBlock: "16px" }}>
            <Navbar />
            <Light />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
